name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Download & install the Android SDK.
      - uses: malinskiy/action-android/install-sdk@release/0.1.1

      # Set up platform tools like adb.
      - run: sdkmanager platform-tools

      # Start ADB (and verify that pathing is working correctly).
      - run: adb devices

      # Verify $ANDROID_HOME is properly set for later Gradle commands.
      - run: echo $ANDROID_HOME

      - name: Run tests
        run: ./gradlew test

      - name: "Run UI Tests"
        uses: faruktoptas/android-github-actions-emulator@latest

      - name: Build project
        run: ./gradlew assemble